### ISSUE TITLE
error in demo.py

### ISSUE THREAD

**Issue by guofengming11** [Svito-zar/gesticulator#30]
![image](https://user-images.githubusercontent.com/67827587/118606089-94676880-b7e9-11eb-9bf1-b48762d3ea30.png)
no module named 'pymo.preprocessing' ,but it is not in requirements.txt
Thanks!!

**Comment by Svito-zar** [comment]
Dear @guofengming11 , please use this script to set up your environment:
https://github.com/Svito-zar/gesticulator/blob/master/install_script.py

**Comment by Svito-zar** [comment]
(As described in the main README file)

**Comment by Svito-zar** [comment]
@guofengming11 , has your issue been resolved?
