### ISSUE TITLE
bvh get downsampled twice?

### ISSUE THREAD

**Issue by philippbb** [Svito-zar/gesticulator#31]
Hi,

In process_data.py line 96 output vectors get downsampled. 

output_vectors = output_vectors[0::3] # Subsample motion (from 60 fsp to 20 fps)

Maybe I understood something wrong, but wasnt this already done in the downsampling step inside the pipeline of bvh2features.py?

kind regards

**Comment by Svito-zar** [comment]
Hi @philippbb,

This was indeed an issue some time ago, but now we don't downsample in `bvh2features.py` anymore:
https://github.com/Svito-zar/gesticulator/blob/master/gesticulator/data_processing/bvh2features.py#L90
The frame rate in this script is set to 60 fps.

Best regards,
Taras

**Comment by philippbb** [comment]
Thank you very much, that made it a bit more understandable for me.

Very cool.

**Comment by Svito-zar** [comment]
sorry for the confusion, we should have made it clear in the code
