### ISSUE TITLE
make bvh datasets

### ISSUE THREAD

**Issue by birdflies** [Svito-zar/gesticulator#35]
Dear Svito-zar, Do you know how to make bvh datasets as same as the format of GENEA Challenge 2020?

**Comment by Svito-zar** [comment]
No, I do not know that.
As this is not an issue, but rather a question - I think it would be better if you place in the [Discussion](https://github.com/Svito-zar/gesticulator/discussions)  instead

**Comment by birdflies** [comment]
Ok, Thanks.
