### ISSUE TITLE
process_data

### ISSUE THREAD

**Issue by birdflies** [Svito-zar/gesticulator#39]
Hi, Svito-zar, It seems that  you do not use all data to train the models. 
In the follow code, you take a random sample according to seq_step, which may reduce real training data.
```
 stop_ind = input_vectors.shape[0] - n_reserved_inds
 input_vectors_final  = np.array([input_vectors[i - args.past_context : i + n_reserved_inds] 
                                     for i in range(start_ind, stop_ind, seq_step)])
stop_ind = output_vectors.shape[0] - n_reserved_inds
output_vectors_final = np.array([output_vectors[i - args.past_context : i + n_reserved_inds]
                                     for i in range(start_ind, stop_ind, seq_step)])
```

**Comment by Svito-zar** [comment]
Hi , @birdflies . 

Not really. I go through the whole dataset from `start_ind` to `stop_ind` with a step of `seq_step`, while doing a sliding window with `args.past_context` past frames and `n_reserved_inds` future frames.

Is it clear what this code does now?

**Comment by birdflies** [comment]
@Svito-zar  Yes, now i understand this code. Thanks for your quickly reply~
