### ISSUE TITLE
Folder setup for training

### ISSUE THREAD

**Issue by aespielberg** [Svito-zar/gesticulator#41]
Hi,

Thank you for the exciting project.  I am trying to get training working, but I am finding documentation about how to process the dataset a bit lacking.

I downloaded the GENEA dataset.  I then took the following steps:

I renamed the downloaded dataset as genea_data (note that this different from the instructions, which suggest putting the downloaded folder in a folder called genea_data, but seems to be consistent with the subsequent steps).

I then, in the data_processing folder, executed:

```
python bvh2features.py --bvh_dir ../../dataset/raw_data/Motion/ --dest_dir ../../dataset/processed_data/
```
(note that there are no defaults for bvh_dir or dest_dir, and the names of these flags do not match the documentation.)

After this, a bunch of .npz files are dumped into processed_data.  I then run split_dataset.py, which creates a train and a test folder in processed_data, but does not distribute the .npz files.  This is clearly not correct, as they should clearly be in train/test folders.

The documentation right now is inaccurate and makes it extremely difficult to reproduce the training procedure.  Can you please explain how this is supposed to look and work?  I am very confused and frustrated.

**Comment by Svito-zar** [comment]
Dear @aespielberg, 
I am very sorry you are having those troubles.
Could you please use the default configuration as suggested in the documentation? The folder name and location should be as expected.
Thank you,
Taras
