### ISSUE TITLE
CUDA error

### ISSUE THREAD

**Issue by zf223669** [Svito-zar/gesticulator#48]
Dear Sir:
I intent to run the training on GPU, however, I got a error below: what`s that problem?  thanks!
/home/zf223669/Mount/anaconda3/envs/Gesticulator/bin/python3.6 /home/zf223669/Mount/Gesticulator/gesticulator/gesticulator/train.py --gpus 1
/home/zf223669/Mount/anaconda3/envs/Gesticulator/lib/python3.6/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.5) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
CUDA_VISIBLE_DEVICES: [0]

  | Name              | Type       | Params
-------------------------------------------------
0 | activation        | Tanh       | 0     
1 | first_layer       | Sequential | 156 K 
2 | second_layer      | Sequential | 131 K 
3 | third_layer       | Sequential | 196 K 
4 | hidden_to_output  | Sequential | 13 K  
5 | encode_speech     | Sequential | 238 K 
6 | reduce_speech_enc | Sequential | 2 M   
7 | conditioning_1    | Sequential | 69 K  
8 | loss              | MSELoss    | 0     
Validation sanity check: 0it [00:00, ?it/s]Traceback (most recent call last):
  File "/home/zf223669/Mount/Gesticulator/gesticulator/gesticulator/train.py", line 69, in <module>
    main(hyperparams)
  File "/home/zf223669/Mount/Gesticulator/gesticulator/gesticulator/train.py", line 43, in main
    trainer.fit(model)
  File "/home/zf223669/Mount/anaconda3/envs/Gesticulator/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 1003, in fit
    results = self.single_gpu_train(model)
  File "/home/zf223669/Mount/anaconda3/envs/Gesticulator/lib/python3.6/site-packages/pytorch_lightning/trainer/distrib_parts.py", line 186, in single_gpu_train
    results = self.run_pretrain_routine(model)
  File "/home/zf223669/Mount/anaconda3/envs/Gesticulator/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 1196, in run_pretrain_routine
    False)
  File "/home/zf223669/Mount/anaconda3/envs/Gesticulator/lib/python3.6/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 293, in _evaluate
    output = self.evaluation_forward(model, batch, batch_idx, dataloader_idx, test_mode)
  File "/home/zf223669/Mount/anaconda3/envs/Gesticulator/lib/python3.6/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 470, in evaluation_forward
    output = model.validation_step(*args)
  File "/home/zf223669/Mount/Gesticulator/gesticulator/gesticulator/model/model.py", line 464, in validation_step
    predicted_gesture = self.forward(speech, text, use_conditioning=True, motion = None, use_teacher_forcing=False)
  File "/home/zf223669/Mount/Gesticulator/gesticulator/gesticulator/model/model.py", line 293, in forward
    speech_encoding_full = self.encode_speech(curr_speech)
  File "/home/zf223669/Mount/anaconda3/envs/Gesticulator/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zf223669/Mount/anaconda3/envs/Gesticulator/lib/python3.6/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/home/zf223669/Mount/anaconda3/envs/Gesticulator/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zf223669/Mount/anaconda3/envs/Gesticulator/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/zf223669/Mount/anaconda3/envs/Gesticulator/lib/python3.6/site-packages/torch/nn/functional.py", line 1372, in linear
    output = input.matmul(weight.t())
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

**Comment by zf223669** [comment]
I used GTX 3090 CUDA 11.4

**Comment by Svito-zar** [comment]
Dear @zf223669, 
Thank you for your question.
Can you run the code on a CPU?
And did you check this post on StackOverflow? https://stackoverflow.com/questions/66600362/runtimeerror-cuda-error-cublas-status-execution-failed-when-calling-cublassge

**Comment by zf223669** [comment]
ok,Thank you! I have a try

**Comment by Svito-zar** [comment]
great. please let me know how it goes. I wonder if this issue is specific to the GPU execution or is it more general

**Comment by zf223669** [comment]
I forged a new rep and updated all the code to python3.8,torch-lighting 1.5, and lastly fixed some bugs to be compatible with the new version. New it could work on GPU(3090, Cuda 11.4). I will check for more detail and plan to update to github, i will let you now after i push to the github. :)

**Comment by zf223669** [comment]
Now it may be some bugs in demo.py. It showed an error below and though it showed that had generated video file, the output is empty:
/home/zf223669/Mount/anaconda3/envs/gesturePy38/bin/python3.8 /home/zf223669/下载/pycharm-professional-2021.3.1/pycharm-2021.3.1/plugins/python/helpers/pydev/pydevd.py --cmd-line --multiproc --qt-support=auto --client 127.0.0.1 --port 40425 --file /home/zf223669/Mount/Gesticulator/gesticulatorPy38/demo/demo.py --audio input/jeremy_howard.wav --text input/jeremy_howard.txt --model_file /home/zf223669/Mount/Gesticulator/gesticulatorPy38/results/last_run/trained_model.ckpt
Spectro
Using bos_token, but it is not set yet.
Using eos_token, but it is not set yet.
Some weights of the model checkpoint at bert-base-cased were not used when initializing BertModel: ['cls.predictions.bias', 'cls.predictions.decoder.weight', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.dense.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Using bos_token, but it is not set yet.
Using eos_token, but it is not set yet.
Using plaintext transcription 'input/jeremy_howard.txt'
Estimating word timings with BERT using syllable count.
Input text:
"Deep learning is an algorithm inspired by how the human brain works, and as a result, it's an algorithm which has no theoretical limitations on what it can do. The more data you give it and the more computation time you give it, the better it gets. The New York Times also showed in this article another extraordinary result of deep learning which I'm going to show you now. It shows that computers can listen and understand."
Generated video: output/generated_motion.mp4

**Comment by Svito-zar** [comment]
> I forged a new rep and updated all the code to python3.8,torch-lighting 1.5, and lastly fixed some bugs to be compatible with the new version. New it could work on GPU(3090, Cuda 11.4). I will check for more detail and plan to update to github, i will let you now after i push to the github. :)

Feel free to make a Push Request afterward

**Comment by Svito-zar** [comment]
As for the latest error - it seems very similar to this one: https://github.com/Svito-zar/gesticulator/issues/42

Can you please verify that PyMo was correctly installed?

**Comment by Svito-zar** [comment]
closed due to inactivity
