### ISSUE TITLE
how to visualize BVH files

### ISSUE THREAD

**Issue by moonryul** [Svito-zar/gesticulator#50]
Hi, Thanks for the wonderful project. 

Please ignore the title of this question. I typed it wrong, but could not change it. 

My question is:

I saw the video for the gesture that the neural net predicts from a given speech and text.
The predicted gesture is in BVH file format. So, I guess that there should be a BVH file viewer in order to generate the video. But I could not find any BVH viewer in the github. So, would you mind pointing to a BVH viewer this project uses?

**Comment by Svito-zar** [comment]
Hi. Thank you for the questions.
You can use the BVH visualizer from the GENEA Challenge 2020 to visualize the BVH file:
https://github.com/jonepatr/genea_visualizer

**Comment by moonryul** [comment]
Wow.
Thanks for the quick answer.
Moon
