### ISSUE TITLE
What is the joint "pCube4" which is defined as a child of Spine3 joint?

### ISSUE THREAD

**Issue by moonryul** [Svito-zar/gesticulator#51]
I noticed that there is "pCube4" joint as a child of Spine3:
	JOINT pCube4
					{
						OFFSET 0.00000 10.91090 1.10792
						CHANNELS 3 Zrotation Xrotation Yrotation
						End site
						{
							OFFSET 0.00000 0.00000 0.00000
						}
					}
	What is this joint?

**Comment by Svito-zar** [comment]
I am not sure about that actually.
Maybe importing the BVH into a Blender or Motion Builder could help to figure it out.
Alternatively, you could consult the documentation for the dataset used: https://trinityspeechgesture.scss.tcd.ie/

**Comment by moonryul** [comment]
Dear Taras,
thanks for the answers. They are quite helpful.
Moon
