### ISSUE TITLE
Cannot use GPU for saving the model predictions during training

### ISSUE THREAD

**Issue by nagyrajmund** [Svito-zar/gesticulator#6]
In `prediction_saving.py/init_prediction_saving_params()`, the input files are initialized on the model's device, which will always be on the CPU during this function (PL puts the model on the right device AFTER the constructor is over).

**Comment by Svito-zar** [comment]
Fixed in the commit https://github.com/Svito-zar/gesticulator/commit/964be66126e04cb863051578803dde55afdda99d
