### ISSUE TITLE
Downsampling the motion data two times

### ISSUE THREAD

**Issue by sunke123** [Svito-zar/gesticulator#8]
Hi Taras, thanks for providing the implementation of gesticulator.

When checking the data processing, I have a question about the downsampling for the motion data.

The motion data is extracted with the fps=20.
https://github.com/Svito-zar/gesticulator/blob/b779f7b0b2ea22fa7310278f9e7c3722b166ded2/gesticulator/data_processing/bvh2features.py#L38

But the motion data is downsampled again when building the dataset. 
https://github.com/Svito-zar/gesticulator/blob/b779f7b0b2ea22fa7310278f9e7c3722b166ded2/gesticulator/data_processing/process_dataset.py#L96

In my opinion, the second downsampling is not reasonable.

**Comment by nagyrajmund** [comment]
Hi Ke, nice catch! 

Taras is currently on a vacation, but we'll get back to you on Monday. If I recall correctly, the second downsampling was necessary because he specified 60 FPS in `bvh2features.py`, but I'll have to check if this is indeed the case.

**Comment by Svito-zar** [comment]
Thanks for flagging this issue, @sunke123 !
I have fixed it now, by removing downsampling from `bvh2features.py` script:
Here is the commit with the fix: https://github.com/Svito-zar/gesticulator/commit/edcfb5ac7302729135975e6a81b3d5fc41391ce6
